### ISSUE TITLE
Error in demo 

### ISSUE THREAD

**Issue by darouwan** [wojtekk/flume-json-interceptor#1]
Here:

> a1.sources.s1.interceptors.i2.serializers = e1
> a1.sources.s1.interceptors.i2.serializers.dt.type=pl.schibsted.flume.interceptor.json.JsonInterceptorMillisSerializer
> a1.sources.s1.interceptors.i2.serializers.dt.pattern=yyyy-MM-dd'T'HH:mm:ssZ
> a1.sources.s1.interceptors.i2.serializers.dt.name=timestamp

should be 

> a1.sources.s1.interceptors.i2.serializers = dt
> a1.sources.s1.interceptors.i2.serializers.dt.type=pl.schibsted.flume.interceptor.json.JsonInterceptorMillisSerializer
> a1.sources.s1.interceptors.i2.serializers.dt.pattern=yyyy-MM-dd'T'HH:mm:ssZ
> a1.sources.s1.interceptors.i2.serializers.dt.name=timestamp

**Comment by wojtekk** [comment]
@darouwan Thanks!
