### ISSUE TITLE
Not work in Flume in HDP 2.6.4

### ISSUE THREAD

**Issue by darouwan** [wojtekk/flume-json-interceptor#2]
Hi buddy, I am upgrading HDP from 2.6.1 to 2.6.4 recently, but this interception seems not working now. 
I use flume-json-interceptor with a kafka source. While with the json interceptor, I kafka source stops to read the data from kafka and no data is written to file channel.  Is there any log to diagnose what the problem is?

**Comment by darouwan** [comment]
I found the potential error:
java.lang.NoSuchFieldError: defaultReader in JsonInterceptor line 65

**Comment by darouwan** [comment]
Hi, I have fixed it by replacing the json path package. I can commit changes if you  like.

**Comment by wojtekk** [comment]
Hi, sorry for late answer - please do commit and PR! Big thanks

**Comment by darouwan** [comment]
Hi, I have created a new pr. Please check it. Thanks.
